"""empty message

Revision ID: 8db6ed7e33ca
Revises: 78abaf1b1740
Create Date: 2019-05-04 09:41:39.656578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db6ed7e33ca'
down_revision = '78abaf1b1740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('sendgrid_domain_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'sendgrid_domain_id')
    # ### end Alembic commands ###
