"""empty message

Revision ID: d3699d3c46a8
Revises: 8db6ed7e33ca
Create Date: 2019-05-04 11:17:52.885651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3699d3c46a8'
down_revision = '8db6ed7e33ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dns', sa.Column('record_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dns', 'record_type')
    # ### end Alembic commands ###
